apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "omnivore.fullname" . }}-migrate
  labels:
    {{- include "omnivore.labels" . | nindent 4 }}
data:
  PG_HOST: {{ .Values.migrate.postgresHost }}
  PG_USER: {{ .Values.postgres.user }}
  PG_PASSWORD: {{ .Values.postgres.password }}
  PG_DB: {{ .Values.postgres.dbName }}
  ELASTIC_URL: {{ .Values.migrate.elasticUrl }}
  ELASTIC_USERNAME: "blank"
  ELASTIC_PASSWORD: "blank"
  PGPASSWORD: {{ .Values.postgres.password }}
