apiVersion: v1
kind: ConfigMap
metadata:
  name: omnivore-postgres-config
data:
  POSTGRES_USER: {{ .Values.postgres.user }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password }}
  POSTGRES_DB: {{ .Values.postgres.dbName }}
  PG_POOL_MAX: "{{ .Values.postgres.pgPoolMax }}"
